name: sunpy-rtd
channels:
    - conda-forge
dependencies:
- astropy >=2.0
- beautifulsoup4
- cairo
- contextlib2
- cycler
- cython
- db
- decorator
- fontconfig
- freetype
- funcsigs
- jbig
- jpeg
- libgfortran
- libpng
- libtiff
- libxml2
- libxslt
- lxml
- matplotlib
- mock
- networkx
- numpy
- openblas
- openssl
- pandas
- pbr
- pillow
- pip
- pixman
- py
- pycairo
- pyparsing
- pyqt
- pytest
- python=3.5
- python-dateutil
- pytz
- qt
- readline
- requests
- scikit-image
- scipy
- setuptools
- sip
- six
- sqlalchemy
- sqlite
- suds-jurko
- sphinx=1.5.6
- sphinx_rtd_theme
- tk
- wheel
- xz
- zlib
- openjpeg
- sphinx-gallery
- glymur
