name: sunpy
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - openjpeg
  - numpy
  - scipy
  - matplotlib
  - pandas
  - astropy
  - parfive
  - sqlalchemy
  - scikit-image
  - glymur
  - beautifulsoup4
  - drms
  - python-dateutil
  - zeep
  - tqdm
  - asdf
  - hypothesis
  - pytest-astropy
  - pytest-cov
  - pytest-mock
  - ruamel.yaml
  - sphinx
  - sphinx-astropy
  - sphinx-gallery
  - towncrier
  - graphviz!=2.42.*
  - pip:
    - sunpy-sphinx-theme
    - jplephem
    - astroquery
    - reproject
    - extension_helpers
