default.extend-ignore-identifiers-re = [
    "ANDed",
    "arange",
    "iy",
    "iy1",
    "iy2",
    "EIS",
    "eis",
    "EIT",
    "eit",
    "HAE",
    "hsi",
    "Hsi",
    "nd",
    "NDData",
    "alog",
    "alog10",
    "FOVs",
    "FOV",
    "ISES",
    # HEK
    "OT",
    "ot",
    # Coords,
    "pn",
    "lightyear",
    "PNGs",
    "setp",
    "precess",
    "precessed",
]
