name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)
variables:
  CI_NAME: Azure Pipelines
  CI_BUILD_ID: $(Build.BuildId)
  CI_BUILD_URL: "https://dev.azure.com/sunpy/sunpy/_build/results?buildId=$(Build.BuildId)"
  CIBW_BUILD: cp36-* cp37-*
  CIBW_SKIP: "*-win32 *-manylinux1_i686"
  CIBW_TEST_COMMAND: pytest -p no:warnings --doctest-rst -m "not figure" --pyargs sunpy
  CIBW_TEST_REQUIRES: sqlalchemy scikit-image glymur beautifulsoup4 drms python-dateutil zeep tqdm asdf hypothesis pytest-astropy pytest-mock

resources:
  repositories:
  - repository: sunpy
    type: github
    endpoint: sunpyorg
    name: sunpy/azure-pipelines-template
    ref: master

trigger:
  tags:
    include:
    - 'v*'
    exclude:
    - '*dev*'
    - '*pre*'
    - '*post*'

jobs:
- template: run-tox-env.yml@sunpy
  parameters:
    name: Linux_37_offline
    os: linux
    tox: py37-offline -- -n=4
    jpeg: True

- template: run-tox-env.yml@sunpy
  parameters:
    name: Linux_36_offline_astropy31
    os: linux
    tox: py36-astropy31 -- -n=4
    jpeg: True

- template: run-tox-env.yml@sunpy
  parameters:
    name: Windows_36_offline
    os: windows
    tox: py36-offline -- -n=4
    jpeg: True


- template: run-tox-env.yml@sunpy
  parameters:
    name: macOS_37_online
    os: macos
    tox: py37-online -- -n=4
    jpeg: True

- template: run-tox-env.yml@sunpy
  parameters:
    name: Linux_36_Conda_offline
    os: linux
    tox: conda -- -n=4
    jpeg: True

- template: run-tox-env.yml@sunpy
  parameters:
    name: Linux_37_astropydev
    os: linux
    tox: py37-astropydev -- -n=4
    jpeg: True

- ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}:
  - template: publish-pypi.yml@sunpy
    parameters:
      dependsOn: [Linux_37_offline,Windows_36_offline,macOS_37_online,Linux_36_Conda_offline]
