name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)
variables:
  CI_NAME: Azure Pipelines
  CI_BUILD_ID: $(Build.BuildId)
  CI_BUILD_URL: "https://dev.azure.com/sunpy/sunpy/_build/results?buildId=$(Build.BuildId)"
  CIBW_BUILD: cp36-* cp37-* cp38-*
  CIBW_SKIP: "*-win32 *-manylinux1_i686"

schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight build
    branches:
      include:
      - master
      - 1.0
      - 1.1
    always: true

resources:
  repositories:
  - repository: OpenAstronomy
    type: github
    endpoint: sunpy
    name: OpenAstronomy/azure-pipelines-templates
    ref: master

trigger:
  branches:
    include:
    - '*'
    exclude:
    - '*backport*'
  tags:
    include:
    - 'v*'
    exclude:
    - '*dev*'
    - '*pre*'
    - '*post*'

jobs:
- template: run-tox-env.yml@OpenAstronomy
  parameters:
    submodules: false
    coverage: codecov
    toxdeps: tox-pypi-filter
    posargs: -n=4
    libraries:
      apt:
        - libopenjp2-7
      brew:
        - openjpeg
      yum:
        - openssl-devel
        - freetype-devel
        - libpng-devel

    envs:
      - macos: py38
        name: py38_test
        posargs: -n=1

      - windows: py37
        name: py37_test

      - linux: py38-online
        name: py38_test_online

      - linux32: py38-32bit
        name: py38_test_32bit

      - linux: codestyle
        name: python_codestyle

      - linux: py38-hypothesis

      - linux: py38-conda
        name: py38_conda_linux
        libraries: {}

      - linux: py38-singlethread-conda
        libraries: {}

      - macos: py38-conda
        name: py38_conda_macos
        libraries: {}

      - linux: py37-oldestdeps
        name: py37_test_oldestdeps

      - linux: py38-devdeps

# On branches which aren't master, and not Pull Requests, build the wheels but only upload them on tags
- ${{ if and(ne(variables['Build.Reason'], 'PullRequest'), not(contains(variables['Build.SourceBranch'], 'master'))) }}:
  - template: publish.yml@OpenAstronomy
    parameters:
      # Only Upload to PyPI on tags
      ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}:
        pypi_connection_name : 'PyPI'
      test_extras: 'dev'
      test_command: 'pytest -p no:warnings --doctest-rst -m "not figure" --pyargs sunpy'
      submodules: false
      targets:
        - wheels_linux
        - wheels_macos
        - sdist
      dependsOn:
        - py37_test
        - py38_test
        - py38_test_online
        - py38_test_32bit
        - py38_test_oldestdeps
        - py38_conda
