name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)
variables:
  CI_NAME: Azure Pipelines
  CI_BUILD_ID: $(Build.BuildId)
  CI_BUILD_URL: "https://dev.azure.com/sunpy/sunpy/_build/results?buildId=$(Build.BuildId)"
  CIBW_BUILD: cp36-* cp37-*
  CIBW_SKIP: "*-win32 *-manylinux1_i686"

resources:
  repositories:
  - repository: OpenAstronomy
    type: github
    endpoint: sunpy
    name: OpenAstronomy/azure-pipelines-templates
    ref: master

trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - 'v*'
    exclude:
    - '*dev*'
    - '*pre*'
    - '*post*'

jobs:
- template: run-tox-env.yml@OpenAstronomy
  parameters:
    submodules: false
    coverage: codecov
    posargs: -n=4
    libraries:
      apt:
        - libopenjpeg5
      brew:
        - openjpeg
    envs:
      - macos: py37-offline
        name: py37_offline

      - windows: py36-offline
        name: py36_offline

      - linux: py37-online
        name: py37_online

      - linux: py36-conda
        name: py36_conda
        libraries: {}

      - linux: py36-astropy31
        name: py36_astropy31

      - linux: py37-astropydev

# On branches which aren't master, and not Pull Requests, build the wheels but only upload them on tags
- ${{ if and(ne(variables['Build.Reason'], 'PullRequest'), not(contains(variables['Build.SourceBranch'], 'master'))) }}:
  - template: publish.yml@OpenAstronomy
    parameters:
      # Only Upload to PyPI on tags
      ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}:
        pypi_connection_name : 'PyPI'
      test_extras: 'dev'
      test_command: 'pytest -p no:warnings --doctest-rst -m "not figure" --pyargs sunpy'
      submodules: false
      targets:
        - wheels_linux
        - wheels_macos
        - sdist
      dependsOn:
        - py37_offline
        - py36_offline
        - py37_online
        - py36_conda
        - py36_astropy31
