name: Automated tests

on:
  push:
    branches:
      - main
      - 3.1
      - 3.0
  pull_request:
    branches:
      - main
      - 3.1
      - 3.0
  # Allow manual runs through the web UI
  workflow_dispatch:

jobs:
  linux-py39:
    uses: ./.github/workflows/python-test-workflow.yml
    with:
      os: ubuntu-latest
      # Advisable to use current python version - 1 here to minimise time spent
      # building wheels for dependencies
      python-version: '3.9'
      tox-env: py39
  linux-py37-oldestdeps:
    uses: ./.github/workflows/python-test-workflow.yml
    needs: linux-py39
    with:
      os: ubuntu-latest
      python-version: '3.7'
      tox-env: py37-oldestdeps
  linux-remote-py39:
    uses: ./.github/workflows/python-test-workflow.yml
    needs: linux-py39
    with:
      os: ubuntu-latest
      python-version: '3.9'
      tox-env: py39-online
  linux-docs-py39:
    uses: ./.github/workflows/python-test-workflow.yml
    needs: linux-py39
    with:
      os: ubuntu-latest
      python-version: '3.9'
      tox-env: build_docs
